name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/exchangers .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/exchangers:latest
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            echo "${{ secrets.ENV_CONTENT }}" > test.env
            sudo docker rm -f exchangers-app-container
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/exchangers:latest
            sudo docker run -d -p 8000:8000 --name exchangers-app-container --env-file test.env ${{ secrets.DOCKER_USERNAME }}/exchangers
            sudo docker image prune -f